### ISSUE TITLE
[Vue warn]: Error in destroyed hook after switching page with vue router

### ISSUE THREAD

**Issue by swerrie** [luiguild/v-bar#5] opened 2017-04-23 11:56 UTC
`TypeError: Cannot read property '__resizeListeners__' of undefined
    at removeResizeListener (eval at <anonymous> (app.js:1087), <anonymous>:154:12)
    at VueComponent.destroyed (eval at <anonymous> (app.js:919), <anonymous>:40:99)
    at callHook (eval at <anonymous> (app.js:721), <anonymous>:2274:21)
    at VueComponent.Vue.$destroy (eval at <anonymous> (app.js:721), <anonymous>:2096:5)
    at pruneCacheEntry (eval at <anonymous> (app.js:721), <anonymous>:4057:29)
    at VueComponent.destroyed (eval at <anonymous> (app.js:721), <anonymous>:4078:7)
    at callHook (eval at <anonymous> (app.js:721), <anonymous>:2274:21)
    at VueComponent.Vue.$destroy (eval at <anonymous> (app.js:721), <anonymous>:2096:5)
    at destroy (eval at <anonymous> (app.js:721), <anonymous>:2963:33)
    at invokeDestroyHook (eval at <anonymous> (app.js:721), <anonymous>:4778:59)`

this looks simular: [link](https://github.com/ElemeFE/element/pull/3837/commits/513d71ae1de143163a22dd5f4b54f2e5858d1e90)

**Comment by luiguild** [comment] 2017-04-26 14:08
Hi @swerrie! I use VBar and Vue-Router in one project with no problems, but I will investigated this and try to reproduce. I will get back to you soon. Thanks!

**Comment by breadlesscode** [comment] 2017-04-26 15:49
Same here.

Laravel Mix  V8.8
Vue  V2.0.1
Vuex V2.1.1
Vue Router V2.1.1

**Comment by DarinLevesque** [comment] 2017-04-26 15:54
Yeah, me too. Same versions as above, without Laravel.

**Comment by luiguild** [comment] 2017-04-26 17:01
Actually I have one project running perfectly with
vue ^2.1.0
vue-router ^2.1.1
webpack ^1.13.2

I created a new project using vue-cli template and I cannot reproduce this error... 

VBar already have many remove listeners:
```
beforeDestroy () {
        document.removeEventListener('mousemove', this.onDrag)
        document.removeEventListener('touchmove', this.onDrag)
        document.removeEventListener('mouseup', this.stopDrag)
        document.removeEventListener('touchend', this.stopDrag)
},
destroyed () {
    removeResizeListener(this.$refs.container, this.resize)
    removeResizeListener(this.$refs.wrapperRef.children[0], this.resize)
},
```

Someone can help me with this?

**Comment by antshil** [comment] 2017-06-27 13:37
Hello!
I have same issue.
If move
```
removeResizeListener(this.$refs.container, this.resize)
removeResizeListener(this.$refs.wrapperRef.children[0], this.resize)
```
from destroyed() to beforeDestroy (), bug will be fixed.
Why "removeResizeListener" was placed in destroyed? Is there any reason for this?

How to reproduce
Use element with <v-bar> in <component> and switch component.

**Comment by luiguild** [comment] 2017-06-27 13:52
Hi @antshil! Thank you for help me with this, I will push these changes today!

**Closed by luiguild** 2017-06-27 13:52 UTC
Labels: bug, help wanted

**Comment by antshil** [comment] 2017-07-01 19:45
Thank you for the new version!
